name: Deploy Apache Update

on:
  push:
    branches:
      - main

jobs:
  update-apache:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Update Apache Configuration
        run: |
          sudo cp -r /home/ubuntu/actions-runner/index.html /var/www/html/index.html
          sudo systemctl restart apache2
        shell: bash

      - name: Cleanup and Terminate Runner
        run: |
          echo "Runner will be terminated."
          /home/ubuntu/actions-runner/svc.sh uninstall
          sudo shutdown now
        shell: bash
