name: Setup Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Launch EC2 Instance
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0d53d72369335a9d6 \
            --count 1 \
            --instance-type t2.micro \
            --key-name nabeel-own-account \
            --security-group-ids sg-02cfe696e1c672b5b \
            --subnet-id subnet-035eb9b659444302b \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          
      - name: Wait for Instance to be Running
        run: |
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}

      - name: Get Instance Public IP
        id: ec2-ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ env.INSTANCE_ID }} \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Configure Self-Hosted Runner
        run: |
          ssh -o StrictHostKeyChecking=no -i nabeel-own-account ubuntu@${{ env.PUBLIC_IP }} << 'EOF'
            mkdir -p ~/actions-runner
            cd ~/actions-runner
            curl -O -L https://github.com/actions/runner/releases/download/v2.304.0/actions-runner-linux-x64-2.304.0.tar.gz
            tar xzf ./actions-runner-linux-x64-2.304.0.tar.gz
            ./config.sh --url https://github.com/your-username/your-repository --token YOUR_RUNNER_TOKEN
            sudo ./svc.sh install
            sudo ./svc.sh start
          EOF


      - name: Update Apache Server
        run: |
          # Run the Apache update script on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i nabeel-own-account ubuntu@${{ env.PUBLIC_IP }} << 'EOF'
            # Update Apache
            sudo cp -r ~/actions-runner/index.html /var/www/html/index.html
            sudo systemctl restart apache2
          EOF



      - name: Terminate EC2 Instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
          aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}









# name: Deploy Apache Update

# on:
#   push:
#     branches:
#       - main

# jobs:
#   update-apache:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Update Apache Configuration
#         run: |
#           echo "Updating Apache server with the latest changes."
#           # Copy updated files to the Apache web directory
#           sudo cp -r /home/ubuntu/actions-runner/index.html /var/www/html/index.html
#           # Restart Apache to apply changes
#           sudo systemctl restart apache2
#         shell: bash

#       - name: Cleanup Runner
#         run: |
#           echo "Cleaning up the runner."
#           cd /home/ubuntu/actions-runner
#           # Stop and uninstall the runner service
#           sudo ./svc.sh stop || true
#           sudo ./svc.sh uninstall || true
#           # Remove runner files
#           sudo rm -rf /home/ubuntu/actions-runner
#           echo "Runner has been cleaned up."
#         shell: bash
